// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rjuttqfoybhjjslvmkhj.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqdXR0cWZveWJoampzbHZta2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIzNzU3MDAsImV4cCI6MjA0Nzk1MTcwMH0.N1UrQJpaciY45BX0YLWT-H8n3tNwd3oSiu9Sf25h-Dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);